spring:
    datasource:
        url: jdbc:mysql://mysql:3306/bbuddytest?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    jpa:
        properties:
            hibernate:
                default_schema: bbuddytest
server:
  port: 4000